In [1]:
# Imports
import pandas as pd
import numpy as np

In [2]:
# Loading df_1, df_2
df_1 = pd.read_pickle('historical_arrears_data_1.pkl')
df_2 = pd.read_pickle('historical_arrears_data_2.pkl')

In [5]:
# Displaying & checking dfs
print(df_1.head())
print()
print(df_1.info())
print()
print(df_2.head())
print()
print(df_2.info())

  Customer_ID  Contract_Term Contract_Start_Date Contract_End_Date  \
0   EJR872837             54          2015-07-21        2021-12-20
1   IMX979868             91          2020-06-06        2021-09-05
2   NQZ020781             90          2016-06-02        2023-05-23
3   ZJE848049             43          2008-08-20        2023-01-12
4   HYT626213             37          2017-06-28        2022-01-18

   Cost_Amount_GBP Regulatory_Compliance Customer_Category  \
0        422562.25                    No       Corporation
1        215224.06                    No       Corporation
2        294362.39                    No       Corporation
3         91318.00                   Yes        Individual
4        809735.65                    No        Individual

   Exposure_Amount_GBP Contract_Status Assistance_Flag Risk_Flag  \
0             17152.49          Closed             Yes        No
1             25252.94         Expired             Yes       Yes
2             62246.83          Active              No       Yes
3             50347.70          Closed             Yes       Yes
4             25850.44          Closed              No       Yes

  Payment_Status  Forbearance_Amount_GBP Payment_Interval  \
0        Current                 1478.58          Monthly
1      Recovered                 1867.41          Monthly
2      Recovered                 1848.59        Quarterly
3     Delinquent                 1101.78         Annually
4      Recovered                  387.66        Quarterly

   Late_Payment_Fees_GBP  Total_Arrears_GBP
0                 861.71            8240.58
1                 978.35           11886.38
2                 950.42            5770.65
3                 203.62            7478.09
4                  17.54            4234.35

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Customer_ID             700000 non-null  object
 1   Contract_Term           700000 non-null  int64
 2   Contract_Start_Date     700000 non-null  object
 3   Contract_End_Date       700000 non-null  object
 4   Cost_Amount_GBP         700000 non-null  float64
 5   Regulatory_Compliance   700000 non-null  object
 6   Customer_Category       700000 non-null  object
 7   Exposure_Amount_GBP     700000 non-null  float64
 8   Contract_Status         700000 non-null  object
 9   Assistance_Flag         700000 non-null  object
 10  Risk_Flag               700000 non-null  object
 11  Payment_Status          700000 non-null  object
 12  Forbearance_Amount_GBP  700000 non-null  float64
 13  Payment_Interval        700000 non-null  object
 14  Late_Payment_Fees_GBP   700000 non-null  float64
 15  Total_Arrears_GBP       700000 non-null  float64
dtypes: float64(5), int64(1), object(10)
memory usage: 85.4+ MB
None

  Customer_ID  Contract_Term Contract_Start_Date Contract_End_Date  \
0   JZM603287           64.0          2010-08-05        2021-08-22
1   JWK625710           67.0          2018-01-04        2022-10-16
2   BQD652277           43.0          2020-04-25        2023-08-02
3   RQJ989396           51.0          2013-08-17        2023-02-27
4   XUJ883199           66.0          2019-11-15        2023-01-23

   Cost_Amount_GBP Regulatory_Compliance    Customer_Category  \
0    339782.683478                    No           Individual
1    270733.814649                    No          Corporation
2    347307.503340                   Yes                  LLC
3    648842.497319                   Yes       Small Business
4    453215.110767                    No  Sole Proprietorship

   Exposure_Amount_GBP Contract_Status Assistance_Flag Risk_Flag  \
0             61302.26          Active              No       Yes
1             26155.05          Active              No       Yes
2             12523.23          Closed             Yes       Yes
3             21502.76          Closed              No        No
4             31980.30          Active              No       Yes

  Payment_Status  Forbearance_Amount_GBP Payment_Interval  \
0      Recovered             1555.625804         Annually
1     Delinquent             1370.896930          Monthly
2        Current              103.747058        Quarterly
3     Delinquent              994.220491         Annually
4        Current              717.888076              NaN

   Late_Payment_Fees_GBP  Total_Arrears_GBP
0                 265.72            3263.20
1                 954.07           15475.72
2                 965.75            7578.64
3                 499.80            7814.54
4                 715.26           17856.30

<class 'pandas.core.frame.DataFrame'>
Index: 665960 entries, 0 to 699999
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Customer_ID             665960 non-null  object
 1   Contract_Term           633781 non-null  float64
 2   Contract_Start_Date     633422 non-null  object
 3   Contract_End_Date       633374 non-null  object
 4   Cost_Amount_GBP         633763 non-null  float64
 5   Regulatory_Compliance   633471 non-null  object
 6   Customer_Category       639563 non-null  object
 7   Exposure_Amount_GBP     633244 non-null  float64
 8   Contract_Status         633250 non-null  object
 9   Assistance_Flag         633654 non-null  object
 10  Risk_Flag               633385 non-null  object
 11  Payment_Status          633594 non-null  object
 12  Forbearance_Amount_GBP  633569 non-null  float64
 13  Payment_Interval        567030 non-null  object
 14  Late_Payment_Fees_GBP   633623 non-null  float64
 15  Total_Arrears_GBP       635778 non-null  float64
dtypes: float64(6), object(10)
memory usage: 86.4+ MB
None

In [6]:
# Identifying missing values
print(df_1.isnull().sum())
print()
print(df_2.isnull().sum())

Customer_ID               0
Contract_Term             0
Contract_Start_Date       0
Contract_End_Date         0
Cost_Amount_GBP           0
Regulatory_Compliance     0
Customer_Category         0
Exposure_Amount_GBP       0
Contract_Status           0
Assistance_Flag           0
Risk_Flag                 0
Payment_Status            0
Forbearance_Amount_GBP    0
Payment_Interval          0
Late_Payment_Fees_GBP     0
Total_Arrears_GBP         0
dtype: int64

Customer_ID                   0
Contract_Term             32179
Contract_Start_Date       32538
Contract_End_Date         32586
Cost_Amount_GBP           32197
Regulatory_Compliance     32489
Customer_Category         26397
Exposure_Amount_GBP       32716
Contract_Status           32710
Assistance_Flag           32306
Risk_Flag                 32575
Payment_Status            32366
Forbearance_Amount_GBP    32391
Payment_Interval          98930
Late_Payment_Fees_GBP     32337
Total_Arrears_GBP         30182
dtype: int64

In [7]:
# Handling missing Customer_ID values
df_1 = df_1.dropna(subset=['Customer_ID'])
df_2 = df_2.dropna(subset=['Customer_ID'])

In [8]:
# Filling numeric missing values with the median and categorical with the mode
for col in df_1.columns:
    if df_1[col].dtype == 'object':
        df_1[col].fillna(df_1[col].mode()[0], inplace=True)
    else:
        df_1[col].fillna(df_1[col].median(), inplace=True)

for col in df_2.columns:
    if df_2[col].dtype == 'object':
        df_2[col].fillna(df_2[col].mode()[0], inplace=True)
    else:
        df_2[col].fillna(df_2[col].median(), inplace=True)

In [9]:
# Converting numeric columns to the correct data type
numeric_columns = ['Contract_Term', 'Cost_Amount_GBP', 'Exposure_Amount_GBP', 'Forbearance_Amount_GBP', 'Late_Payment_Fees_GBP', 'Total_Arrears_GBP']

for col in numeric_columns:
    df_1[col] = pd.to_numeric(df_1[col])
    df_2[col] = pd.to_numeric(df_2[col])

In [10]:
# Converting Contract_Term to int64
df_1['Contract_Term'] = df_1['Contract_Term'].astype('int64')
df_2['Contract_Term'] = df_2['Contract_Term'].astype('int64')

In [11]:
# Ensuring categorical data is consistent
categorical_columns = ['Regulatory_Compliance', 'Customer_Category', 'Contract_Status', 'Assistance_Flag', 'Risk_Flag', 'Payment_Status', 'Payment_Interval']

for col in categorical_columns:
    df_1[col] = df_1[col].astype('category')
    df_2[col] = df_2[col].astype('category')

In [12]:
# Dropping Contract_Start_Date and Contract_End_Date
df_1.drop(columns=['Contract_Start_Date', 'Contract_End_Date'], inplace=True)
df_2.drop(columns=['Contract_Start_Date', 'Contract_End_Date'], inplace=True)

In [13]:
# Final check of data types and missing values
print(df_1.head())
print()
print(df_1.info())
print()
print(df_2.head())
print()
print(df_2.info())

  Customer_ID  Contract_Term  Cost_Amount_GBP Regulatory_Compliance  \
0   EJR872837             54        422562.25                    No
1   IMX979868             91        215224.06                    No
2   NQZ020781             90        294362.39                    No
3   ZJE848049             43         91318.00                   Yes
4   HYT626213             37        809735.65                    No

  Customer_Category  Exposure_Amount_GBP Contract_Status Assistance_Flag  \
0       Corporation             17152.49          Closed             Yes
1       Corporation             25252.94         Expired             Yes
2       Corporation             62246.83          Active              No
3        Individual             50347.70          Closed             Yes
4        Individual             25850.44          Closed              No

  Risk_Flag Payment_Status  Forbearance_Amount_GBP Payment_Interval  \
0        No        Current                 1478.58          Monthly
1       Yes      Recovered                 1867.41          Monthly
2       Yes      Recovered                 1848.59        Quarterly
3       Yes     Delinquent                 1101.78         Annually
4       Yes      Recovered                  387.66        Quarterly

   Late_Payment_Fees_GBP  Total_Arrears_GBP
0                 861.71            8240.58
1                 978.35           11886.38
2                 950.42            5770.65
3                 203.62            7478.09
4                  17.54            4234.35

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Customer_ID             700000 non-null  object
 1   Contract_Term           700000 non-null  int64
 2   Cost_Amount_GBP         700000 non-null  float64
 3   Regulatory_Compliance   700000 non-null  category
 4   Customer_Category       700000 non-null  category
 5   Exposure_Amount_GBP     700000 non-null  float64
 6   Contract_Status         700000 non-null  category
 7   Assistance_Flag         700000 non-null  category
 8   Risk_Flag               700000 non-null  category
 9   Payment_Status          700000 non-null  category
 10  Forbearance_Amount_GBP  700000 non-null  float64
 11  Payment_Interval        700000 non-null  category
 12  Late_Payment_Fees_GBP   700000 non-null  float64
 13  Total_Arrears_GBP       700000 non-null  float64
dtypes: category(7), float64(5), int64(1), object(1)
memory usage: 42.1+ MB
None

  Customer_ID  Contract_Term  Cost_Amount_GBP Regulatory_Compliance  \
0   JZM603287             64    339782.683478                    No
1   JWK625710             67    270733.814649                    No
2   BQD652277             43    347307.503340                   Yes
3   RQJ989396             51    648842.497319                   Yes
4   XUJ883199             66    453215.110767                    No

     Customer_Category  Exposure_Amount_GBP Contract_Status Assistance_Flag  \
0           Individual             61302.26          Active              No
1          Corporation             26155.05          Active              No
2                  LLC             12523.23          Closed             Yes
3       Small Business             21502.76          Closed              No
4  Sole Proprietorship             31980.30          Active              No

  Risk_Flag Payment_Status  Forbearance_Amount_GBP Payment_Interval  \
0       Yes      Recovered             1555.625804         Annually
1       Yes     Delinquent             1370.896930          Monthly
2       Yes        Current              103.747058        Quarterly
3        No     Delinquent              994.220491         Annually
4       Yes        Current              717.888076         Annually

   Late_Payment_Fees_GBP  Total_Arrears_GBP
0                 265.72            3263.20
1                 954.07           15475.72
2                 965.75            7578.64
3                 499.80            7814.54
4                 715.26           17856.30

<class 'pandas.core.frame.DataFrame'>
Index: 665960 entries, 0 to 699999
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Customer_ID             665960 non-null  object
 1   Contract_Term           665960 non-null  int64
 2   Cost_Amount_GBP         665960 non-null  float64
 3   Regulatory_Compliance   665960 non-null  category
 4   Customer_Category       665960 non-null  category
 5   Exposure_Amount_GBP     665960 non-null  float64
 6   Contract_Status         665960 non-null  category
 7   Assistance_Flag         665960 non-null  category
 8   Risk_Flag               665960 non-null  category
 9   Payment_Status          665960 non-null  category
 10  Forbearance_Amount_GBP  665960 non-null  float64
 11  Payment_Interval        665960 non-null  category
 12  Late_Payment_Fees_GBP   665960 non-null  float64
 13  Total_Arrears_GBP       665960 non-null  float64
dtypes: category(7), float64(5), int64(1), object(1)
memory usage: 45.1+ MB
None

In [ ]:
# Saving as cleaned datasets in pickle file to data structure and types
df_1.to_pickle('cleaned_historical_arrears_data_1.pkl')
df_2.to_pickle('cleaned_historical_arrears_data_2.pkl')